# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Sparsifier": "01a_sparsifier.ipynb",
         "SparsifyCallback": "02_sparsify_callback.ipynb",
         "Pruner": "02a_pruner.ipynb",
         "KnowledgeDistillation": "05_knowledge_distillation.ipynb",
         "SoftTarget": "05_knowledge_distillation.ipynb",
         "LogitsRegression": "05_knowledge_distillation.ipynb",
         "WeightRegression": "05_knowledge_distillation.ipynb",
         "BN_Folder": "06_bn_folding.ipynb",
         "FC_Decomposer": "06b_fc_decomposer.ipynb",
         "RegularizationCallback": "07_regularizer.ipynb",
         "Criteria": "0b_criteria.ipynb",
         "granularities": "0b_criteria.ipynb",
         "random": "0b_criteria.ipynb",
         "large_final": "0b_criteria.ipynb",
         "small_final": "0b_criteria.ipynb",
         "large_init": "0b_criteria.ipynb",
         "small_init": "0b_criteria.ipynb",
         "large_init_large_final": "0b_criteria.ipynb",
         "small_init_small_final": "0b_criteria.ipynb",
         "magnitude_increase": "0b_criteria.ipynb",
         "movement": "0b_criteria.ipynb",
         "updating_magnitude_increase": "0b_criteria.ipynb",
         "updating_movement": "0b_criteria.ipynb",
         "grad_crit": "0b_criteria.ipynb",
         "one_shot": "0c_schedules.ipynb",
         "iterative": "0c_schedules.ipynb",
         "sched_agp": "0c_schedules.ipynb",
         "sched_onecycle": "0c_schedules.ipynb"}

modules = ["sparse/sparsifier.py",
           "sparse/sparsify_callback.py",
           "sparse/pruner.py",
           "distill/distillation_callback.py",
           "misc/bn_folding.py",
           "misc/fc_decomposer.py",
           "regularization/regularization_callback.py",
           "sparse/criteria.py",
           "sparse/schedule.py"]

doc_url = "https://nathanhubens.github.io/fasterai/"

git_url = "https://github.com/nathanhubens/fasterai/tree/master/"

def custom_doc_links(name): return None
