# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Sparsifier": "01a_sparsifier.ipynb",
         "SparsifyCallback": "02_sparsify_callback.ipynb",
         "KnowledgeDistillation": "05_knowledge_distillation.ipynb",
         "DistillationLoss": "05_knowledge_distillation.ipynb",
         "l1_norm": "0b_criteria.ipynb",
         "grad_crit": "0b_criteria.ipynb",
         "movement": "0b_criteria.ipynb",
         "iterative": "0c_schedules.ipynb",
         "one_shot": "0c_schedules.ipynb",
         "sched_agp": "0c_schedules.ipynb",
         "dsd": "0c_schedules.ipynb"}

modules = ["sparse/sparsifier.py",
           "sparse/sparsify_callback.py",
           "distill/distillation_callback.py",
           "sparse/criteria.py",
           "sparse/schedule.py"]

doc_url = "https://nathanhubens.github.io/fasterai/"

git_url = "https://github.com/nathanhubens/fasterai/tree/master/"

def custom_doc_links(name): return None
